In [381]:
import numpy as np
import seaborn as sns
import pandas as pd
from datetime import datetime

In [382]:
x = np.array([-2, -1, 0, 1, 2, 3])
type(x), x.ndim, x.shape

(numpy.ndarray, 1, (6,))

In [383]:
# zadanie 1
x = np.zeros((2, 4))
print(x.ndim, x.shape)

x.resize((2, 6))
x

2 (2, 4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [384]:
# zadanie 2
x = np.arange(0, 10, 2) # zadany przyrost 2
a, b = (10, 15)
y = np.arange(a, b)

x, y

(array([0, 2, 4, 6, 8]), array([10, 11, 12, 13, 14]))

In [385]:
# zadanie 3
x = np.identity(3)
print(x)

# zadanie 4
x = np.matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
x[0][0] = 10
x.ndim, x.shape, x

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

(2,
 (4, 2),
 matrix([[10, 10],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]]))

In [386]:
# zadanie 5
X = np.asmatrix(np.random.rand(3, 2))
Y = np.asmatrix(np.random.rand(2, 4))

print('X, Y = ', X, Y)
operations = '+-/*'

for op in operations:
    try:
        print(f'X {op} Y = ', eval(f'X{op}Y'))
    except:
        pass

X, Y =  [[0.56101862 0.95695874]
 [0.0363793  0.02076956]
 [0.08346459 0.33246646]] [[0.21135219 0.96614541 0.38687809 0.32302636]
 [0.88372815 0.05257878 0.56846795 0.65072281]]
X * Y =  [[0.9642639  0.59234129 0.76104619 0.80393869]
 [0.02604349 0.03623973 0.02588118 0.0252667 ]
 [0.31145039 0.09811961 0.22128715 0.24330477]]

In [387]:
# zadanie 5 (wersja dwa)
X = np.asmatrix(np.random.rand(3, 2))
Y = np.asmatrix(np.random.rand(3, 2))

print('X, Y = ', X, Y)
operations = '+-/*'

for op in operations:
    try:
        print(f'X {op} Y = ', eval(f'X{op}Y'))
    except:
        pass

X, Y =  [[0.7043399  0.1979186 ]
 [0.50103585 0.17862398]
 [0.73975982 0.25464458]] [[0.82929973 0.07381503]
 [0.27588819 0.91602615]
 [0.69654166 0.78196089]]
X + Y =  [[1.53363963 0.27173363]
 [0.77692404 1.09465013]
 [1.43630148 1.03660547]]
X - Y =  [[-0.12495983  0.12410356]
 [ 0.22514765 -0.73740217]
 [ 0.04321816 -0.52731632]]
X / Y =  [[0.84931886 2.68127761]
 [1.81608297 0.19499878]
 [1.06204676 0.32564873]]

In [388]:
iris = np.array(sns.load_dataset("iris").iloc[:,0:4])
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [389]:
# zadanie 6
avg = np.mean(iris)
std = np.std(iris, ddof=0)
print(avg, std)

(iris - avg) / std

3.4644999999999997 1.9738430577598278

array([[ 0.82858665,  0.01798522, -1.04592915, -1.65388022],
       [ 0.72726147, -0.23532773, -1.04592915, -1.65388022],
       [ 0.62593629, -0.13400255, -1.09659174, -1.65388022],
       [ 0.5752737 , -0.18466514, -0.99526657, -1.65388022],
       [ 0.77792406,  0.06864781, -1.04592915, -1.65388022],
       [ 0.98057441,  0.22063558, -0.89394139, -1.55255505],
       [ 0.5752737 , -0.03267737, -1.04592915, -1.60321764],
       [ 0.77792406, -0.03267737, -0.99526657, -1.65388022],
       [ 0.47394852, -0.28599032, -1.04592915, -1.65388022],
       [ 0.72726147, -0.18466514, -0.99526657, -1.70454281],
       [ 0.98057441,  0.1193104 , -0.99526657, -1.65388022],
       [ 0.67659888, -0.03267737, -0.94460398, -1.65388022],
       [ 0.67659888, -0.23532773, -1.04592915, -1.70454281],
       [ 0.42328593, -0.23532773, -1.19791692, -1.70454281],
       [ 1.18322477,  0.27129817, -1.14725433, -1.65388022],
       [ 1.13256218,  0.47394852, -0.99526657, -1.55255505],
       [ 0.98057441,  0.22063558, -1.09659174, -1.55255505],
       [ 0.82858665,  0.01798522, -1.04592915, -1.60321764],
       [ 1.13256218,  0.16997299, -0.89394139, -1.60321764],
       [ 0.82858665,  0.16997299, -0.99526657, -1.60321764],
       [ 0.98057441, -0.03267737, -0.89394139, -1.65388022],
       [ 0.82858665,  0.1193104 , -0.99526657, -1.55255505],
       [ 0.5752737 ,  0.06864781, -1.24857951, -1.65388022],
       [ 0.82858665, -0.08333996, -0.89394139, -1.50189246],
       [ 0.67659888, -0.03267737, -0.79261621, -1.65388022],
       [ 0.77792406, -0.23532773, -0.94460398, -1.65388022],
       [ 0.77792406, -0.03267737, -0.94460398, -1.55255505],
       [ 0.87924924,  0.01798522, -0.99526657, -1.65388022],
       [ 0.87924924, -0.03267737, -1.04592915, -1.65388022],
       [ 0.62593629, -0.13400255, -0.94460398, -1.65388022],
       [ 0.67659888, -0.18466514, -0.94460398, -1.65388022],
       [ 0.98057441, -0.03267737, -0.99526657, -1.55255505],
       [ 0.87924924,  0.32196075, -0.99526657, -1.70454281],
       [ 1.031237  ,  0.37262334, -1.04592915, -1.65388022],
       [ 0.72726147, -0.18466514, -0.99526657, -1.65388022],
       [ 0.77792406, -0.13400255, -1.14725433, -1.65388022],
       [ 1.031237  ,  0.01798522, -1.09659174, -1.65388022],
       [ 0.72726147,  0.06864781, -1.04592915, -1.70454281],
       [ 0.47394852, -0.23532773, -1.09659174, -1.65388022],
       [ 0.82858665, -0.03267737, -0.99526657, -1.65388022],
       [ 0.77792406,  0.01798522, -1.09659174, -1.60321764],
       [ 0.52461111, -0.58996585, -1.09659174, -1.60321764],
       [ 0.47394852, -0.13400255, -1.09659174, -1.65388022],
       [ 0.77792406,  0.01798522, -0.94460398, -1.45122987],
       [ 0.82858665,  0.16997299, -0.79261621, -1.55255505],
       [ 0.67659888, -0.23532773, -1.04592915, -1.60321764],
       [ 0.82858665,  0.16997299, -0.94460398, -1.65388022],
       [ 0.5752737 , -0.13400255, -1.04592915, -1.65388022],
       [ 0.92991182,  0.1193104 , -0.99526657, -1.65388022],
       [ 0.77792406, -0.08333996, -1.04592915, -1.65388022],
       [ 1.79117584, -0.13400255,  0.62593629, -1.04592915],
       [ 1.48720031, -0.13400255,  0.52461111, -0.99526657],
       [ 1.74051325, -0.18466514,  0.72726147, -0.99526657],
       [ 1.031237  , -0.58996585,  0.27129817, -1.09659174],
       [ 1.5378629 , -0.33665291,  0.5752737 , -0.99526657],
       [ 1.13256218, -0.33665291,  0.52461111, -1.09659174],
       [ 1.43653772, -0.08333996,  0.62593629, -0.94460398],
       [ 0.72726147, -0.53930326, -0.08333996, -1.24857951],
       [ 1.58852548, -0.28599032,  0.5752737 , -1.09659174],
       [ 0.87924924, -0.38731549,  0.22063558, -1.04592915],
       [ 0.77792406, -0.74195362,  0.01798522, -1.24857951],
       [ 1.23388736, -0.23532773,  0.37262334, -0.99526657],
       [ 1.28454995, -0.64062844,  0.27129817, -1.24857951],
       [ 1.33521254, -0.28599032,  0.62593629, -1.04592915],
       [ 1.08189959, -0.28599032,  0.06864781, -1.09659174],
       [ 1.63918807, -0.18466514,  0.47394852, -1.04592915],
       [ 1.08189959, -0.23532773,  0.52461111, -0.99526657],
       [ 1.18322477, -0.38731549,  0.32196075, -1.24857951],
       [ 1.38587513, -0.64062844,  0.52461111, -0.99526657],
       [ 1.08189959, -0.48864067,  0.22063558, -1.19791692],
       [ 1.23388736, -0.13400255,  0.67659888, -0.8432788 ],
       [ 1.33521254, -0.33665291,  0.27129817, -1.09659174],
       [ 1.43653772, -0.48864067,  0.72726147, -0.99526657],
       [ 1.33521254, -0.33665291,  0.62593629, -1.14725433],
       [ 1.48720031, -0.28599032,  0.42328593, -1.09659174],
       [ 1.58852548, -0.23532773,  0.47394852, -1.04592915],
       [ 1.68985066, -0.33665291,  0.67659888, -1.04592915],
       [ 1.63918807, -0.23532773,  0.77792406, -0.89394139],
       [ 1.28454995, -0.28599032,  0.52461111, -0.99526657],
       [ 1.13256218, -0.43797808,  0.01798522, -1.24857951],
       [ 1.031237  , -0.53930326,  0.16997299, -1.19791692],
       [ 1.031237  , -0.53930326,  0.1193104 , -1.24857951],
       [ 1.18322477, -0.38731549,  0.22063558, -1.14725433],
       [ 1.28454995, -0.38731549,  0.82858665, -0.94460398],
       [ 0.98057441, -0.23532773,  0.52461111, -0.99526657],
       [ 1.28454995, -0.03267737,  0.52461111, -0.94460398],
       [ 1.63918807, -0.18466514,  0.62593629, -0.99526657],
       [ 1.43653772, -0.58996585,  0.47394852, -1.09659174],
       [ 1.08189959, -0.23532773,  0.32196075, -1.09659174],
       [ 1.031237  , -0.48864067,  0.27129817, -1.09659174],
       [ 1.031237  , -0.43797808,  0.47394852, -1.14725433],
       [ 1.33521254, -0.23532773,  0.5752737 , -1.04592915],
       [ 1.18322477, -0.43797808,  0.27129817, -1.14725433],
       [ 0.77792406, -0.58996585, -0.08333996, -1.24857951],
       [ 1.08189959, -0.38731549,  0.37262334, -1.09659174],
       [ 1.13256218, -0.23532773,  0.37262334, -1.14725433],
       [ 1.13256218, -0.28599032,  0.37262334, -1.09659174],
       [ 1.38587513, -0.28599032,  0.42328593, -1.09659174],
       [ 0.82858665, -0.48864067, -0.23532773, -1.19791692],
       [ 1.13256218, -0.33665291,  0.32196075, -1.09659174],
       [ 1.43653772, -0.08333996,  1.28454995, -0.48864067],
       [ 1.18322477, -0.38731549,  0.82858665, -0.79261621],
       [ 1.84183843, -0.23532773,  1.23388736, -0.69129103],
       [ 1.43653772, -0.28599032,  1.08189959, -0.8432788 ],
       [ 1.5378629 , -0.23532773,  1.18322477, -0.64062844],
       [ 2.09515138, -0.23532773,  1.58852548, -0.69129103],
       [ 0.72726147, -0.48864067,  0.52461111, -0.89394139],
       [ 1.94316361, -0.28599032,  1.43653772, -0.8432788 ],
       [ 1.63918807, -0.48864067,  1.18322477, -0.8432788 ],
       [ 1.89250102,  0.06864781,  1.33521254, -0.48864067],
       [ 1.5378629 , -0.13400255,  0.82858665, -0.74195362],
       [ 1.48720031, -0.38731549,  0.92991182, -0.79261621],
       [ 1.68985066, -0.23532773,  1.031237  , -0.69129103],
       [ 1.13256218, -0.48864067,  0.77792406, -0.74195362],
       [ 1.18322477, -0.33665291,  0.82858665, -0.53930326],
       [ 1.48720031, -0.13400255,  0.92991182, -0.58996585],
       [ 1.5378629 , -0.23532773,  1.031237  , -0.8432788 ],
       [ 2.14581397,  0.16997299,  1.63918807, -0.64062844],
       [ 2.14581397, -0.43797808,  1.74051325, -0.58996585],
       [ 1.28454995, -0.64062844,  0.77792406, -0.99526657],
       [ 1.74051325, -0.13400255,  1.13256218, -0.58996585],
       [ 1.08189959, -0.33665291,  0.72726147, -0.74195362],
       [ 2.14581397, -0.33665291,  1.63918807, -0.74195362],
       [ 1.43653772, -0.38731549,  0.72726147, -0.8432788 ],
       [ 1.63918807, -0.08333996,  1.13256218, -0.69129103],
       [ 1.89250102, -0.13400255,  1.28454995, -0.8432788 ],
       [ 1.38587513, -0.33665291,  0.67659888, -0.8432788 ],
       [ 1.33521254, -0.23532773,  0.72726147, -0.8432788 ],
       [ 1.48720031, -0.33665291,  1.08189959, -0.69129103],
       [ 1.89250102, -0.23532773,  1.18322477, -0.94460398],
       [ 1.9938262 , -0.33665291,  1.33521254, -0.79261621],
       [ 2.24713914,  0.16997299,  1.48720031, -0.74195362],
       [ 1.48720031, -0.33665291,  1.08189959, -0.64062844],
       [ 1.43653772, -0.33665291,  0.82858665, -0.99526657],
       [ 1.33521254, -0.43797808,  1.08189959, -1.04592915],
       [ 2.14581397, -0.23532773,  1.33521254, -0.58996585],
       [ 1.43653772, -0.03267737,  1.08189959, -0.53930326],
       [ 1.48720031, -0.18466514,  1.031237  , -0.8432788 ],
       [ 1.28454995, -0.23532773,  0.67659888, -0.8432788 ],
       [ 1.74051325, -0.18466514,  0.98057441, -0.69129103],
       [ 1.63918807, -0.18466514,  1.08189959, -0.53930326],
       [ 1.74051325, -0.18466514,  0.82858665, -0.58996585],
       [ 1.18322477, -0.38731549,  0.82858665, -0.79261621],
       [ 1.68985066, -0.13400255,  1.23388736, -0.58996585],
       [ 1.63918807, -0.08333996,  1.13256218, -0.48864067],
       [ 1.63918807, -0.23532773,  0.87924924, -0.58996585],
       [ 1.43653772, -0.48864067,  0.77792406, -0.79261621],
       [ 1.5378629 , -0.23532773,  0.87924924, -0.74195362],
       [ 1.38587513, -0.03267737,  0.98057441, -0.58996585],
       [ 1.23388736, -0.23532773,  0.82858665, -0.8432788 ]])

In [390]:
# zadanie 7
def partition(array, begin, end):
    pivot = begin
    for i in range(begin+1, end+1):
        if array[i] <= array[begin]:
            pivot += 1
            array[i], array[pivot] = array[pivot], array[i]
    array[pivot], array[begin] = array[begin], array[pivot]
    return pivot

def quicksort(array, begin=0, end=None):
    if end is None:
        end = len(array) - 1
    def q(array, begin, end):
        if begin >= end:
            return
        pivot = partition(array, begin, end)
        q(array, begin, pivot-1)
        q(array, pivot+1, end)
    return q(array, begin, end)

x = np.random.rand(10)
print(x)
quicksort(x)
x

[0.75643968 0.85199031 0.30821313 0.83120879 0.31693313 0.85027494
 0.85654733 0.98413406 0.49134356 0.81284433]

array([0.30821313, 0.31693313, 0.49134356, 0.75643968, 0.81284433,
       0.83120879, 0.85027494, 0.85199031, 0.85654733, 0.98413406])

In [391]:
# zadanie 8
x = np.array([-1, 2, 1, 3, 3])
vals, counts = np.unique(x, return_counts=True)
index = np.argmax(counts)
'mode = ', x[index]

('mode = ', 3)

In [392]:
# zadanie 9
flights = sns.load_dataset("flights")
tips = sns.load_dataset("tips")
iris = sns.load_dataset("iris")

flights.shape, tips.shape, iris.shape

((144, 3), (244, 7), (150, 5))

In [393]:
flights.head(), tips.head(), iris.head()

(   year month  passengers
 0  1949   Jan         112
 1  1949   Feb         118
 2  1949   Mar         132
 3  1949   Apr         129
 4  1949   May         121,
    total_bill   tip     sex smoker  day    time  size
 0       16.99  1.01  Female     No  Sun  Dinner     2
 1       10.34  1.66    Male     No  Sun  Dinner     3
 2       21.01  3.50    Male     No  Sun  Dinner     3
 3       23.68  3.31    Male     No  Sun  Dinner     2
 4       24.59  3.61  Female     No  Sun  Dinner     4,
    sepal_length  sepal_width  petal_length  petal_width species
 0           5.1          3.5           1.4          0.2  setosa
 1           4.9          3.0           1.4          0.2  setosa
 2           4.7          3.2           1.3          0.2  setosa
 3           4.6          3.1           1.5          0.2  setosa
 4           5.0          3.6           1.4          0.2  setosa)

In [394]:
flights.tail(), tips.tail(), iris.tail()

(     year month  passengers
 139  1960   Aug         606
 140  1960   Sep         508
 141  1960   Oct         461
 142  1960   Nov         390
 143  1960   Dec         432,
      total_bill   tip     sex smoker   day    time  size
 239       29.03  5.92    Male     No   Sat  Dinner     3
 240       27.18  2.00  Female    Yes   Sat  Dinner     2
 241       22.67  2.00    Male    Yes   Sat  Dinner     2
 242       17.82  1.75    Male     No   Sat  Dinner     2
 243       18.78  3.00  Female     No  Thur  Dinner     2,
      sepal_length  sepal_width  petal_length  petal_width    species
 145           6.7          3.0           5.2          2.3  virginica
 146           6.3          2.5           5.0          1.9  virginica
 147           6.5          3.0           5.2          2.0  virginica
 148           6.2          3.4           5.4          2.3  virginica
 149           5.9          3.0           5.1          1.8  virginica)

In [395]:
flights.info(), tips.info(), iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        144 non-null    int64
 1   month       144 non-null    category
 2   passengers  144 non-null    int64
dtypes: category(1), int64(2)
memory usage: 2.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

(None, None, None)

In [396]:
# zadanie 10
first_row = flights.iloc[0]
dt = datetime.strptime(f'{first_row.year} {first_row.month}', '%Y %b')
dt

datetime.datetime(1949, 1, 1, 0, 0)

In [397]:
flights['date'] = flights.apply(lambda row: datetime.strptime(f'{row.year} {row.month}', '%Y %b'), axis=1)
flights

     year month  passengers       date
0    1949   Jan         112 1949-01-01
1    1949   Feb         118 1949-02-01
2    1949   Mar         132 1949-03-01
3    1949   Apr         129 1949-04-01
4    1949   May         121 1949-05-01
..    ...   ...         ...        ...
139  1960   Aug         606 1960-08-01
140  1960   Sep         508 1960-09-01
141  1960   Oct         461 1960-10-01
142  1960   Nov         390 1960-11-01
143  1960   Dec         432 1960-12-01

[144 rows x 4 columns]

In [398]:
# zadanie 11
iris_names = iris['species']
X = iris.loc[:, iris.columns != 'species']

# mean standartization
iris_normilized_mean = (X - X.mean()) / X.std()
# min-max standartization
iris_normalized_minmax = (X - X.min()) / (X.max() - X.min())

iris_normilized_mean, iris_normalized_minmax

(     sepal_length  sepal_width  petal_length  petal_width
 0       -0.897674     1.015602     -1.335752    -1.311052
 1       -1.139200    -0.131539     -1.335752    -1.311052
 2       -1.380727     0.327318     -1.392399    -1.311052
 3       -1.501490     0.097889     -1.279104    -1.311052
 4       -1.018437     1.245030     -1.335752    -1.311052
 ..            ...          ...           ...          ...
 145      1.034539    -0.131539      0.816859     1.443994
 146      0.551486    -1.278680      0.703564     0.919223
 147      0.793012    -0.131539      0.816859     1.050416
 148      0.430722     0.786174      0.930154     1.443994
 149      0.068433    -0.131539      0.760211     0.788031

 [150 rows x 4 columns],
      sepal_length  sepal_width  petal_length  petal_width
 0        0.222222     0.625000      0.067797     0.041667
 1        0.166667     0.416667      0.067797     0.041667
 2        0.111111     0.500000      0.050847     0.041667
 3        0.083333     0.458333      0.084746     0.041667
 4        0.194444     0.666667      0.067797     0.041667
 ..            ...          ...           ...          ...
 145      0.666667     0.416667      0.711864     0.916667
 146      0.555556     0.208333      0.677966     0.750000
 147      0.611111     0.416667      0.711864     0.791667
 148      0.527778     0.583333      0.745763     0.916667
 149      0.444444     0.416667      0.694915     0.708333

 [150 rows x 4 columns])

In [399]:
# zadanie 12
perc_80 = iris.sample(frac=0.8)
perc_20 = iris.sample(frac=0.2)

print(perc_80.shape, perc_20.shape)

# lub 
perc_80 = iris.head(int(len(iris) * 0.8))
perc_20 = iris.tail(int(len(iris) * 0.2))

perc_80.shape, perc_20.shape

(120, 5) (30, 5)

((120, 5), (30, 5))

In [400]:
# zadanie 12

avg = flights.groupby(['year']).mean()
std = flights.groupby(['year']).std()
quantile = flights.groupby(['year']).quantile(0.5)

avg, std, quantile

/var/folders/qc/qnvdlk4d3d1gy79wdk5_jrnm0000gn/T/ipykernel_2235/3028973603.py:5: FutureWarning: Dropping invalid columns in DataFrameGroupBy.quantile is deprecated. In a future version, a TypeError will be raised. Before calling .quantile, select only columns which should be valid for the function.
  quantile = flights.groupby(['year']).quantile(0.5)

(      passengers
 year
 1949  126.666667
 1950  139.666667
 1951  170.166667
 1952  197.000000
 1953  225.000000
 1954  238.916667
 1955  284.000000
 1956  328.250000
 1957  368.416667
 1958  381.000000
 1959  428.333333
 1960  476.166667,
       passengers
 year
 1949   13.720147
 1950   19.070841
 1951   18.438267
 1952   22.966379
 1953   28.466887
 1954   34.924486
 1955   42.140458
 1956   47.861780
 1957   57.890898
 1958   64.530472
 1959   69.830097
 1960   77.737125,
       passengers       date
 year
 1949       125.0 1949-06-16
 1950       137.5 1950-06-16
 1951       169.0 1951-06-16
 1952       192.0 1952-06-16
 1953       232.0 1953-06-16
 1954       231.5 1954-06-16
 1955       272.0 1955-06-16
 1956       315.0 1956-06-16
 1957       351.5 1957-06-16
 1958       360.5 1958-06-16
 1959       406.5 1959-06-16
 1960       461.0 1960-06-16)